version: '3.8'

services:
  database:
    image: postgres:13-alpine
    container_name: kupipodariday-database
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    networks:
      - backend-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kupipodariday-backend
    env_file:
      - .env
      - ./backend/.env
    ports:
      - "4000:3000"
    depends_on:
      - database
    networks:
      - backend-network
      - frontend-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kupipodariday-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - frontend-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge