version: '3.8'

services:
  database:
    image: postgres:13-alpine
    container_name: kupipodariday-postgres
    environment:
      POSTGRES_DB: kupipodariday
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kupipodariday-backend
    environment:
      PORT: 4000
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: kupipodariday
      DB_USERNAME: student
      DB_PASSWORD: student
      DB_SYNC: true
      JWT_SECRET: super-strong-secret
      JWT_EXPIRES_IN: 7d
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge